# Generated by Django 2.1.5 on 2022-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ManyToManyField(to='blog.BlogType'),
        ),
    ]
